### ISSUE TITLE
Timer too close problem

### ISSUE THREAD

**Issue by wofidkr** [Mellow-3D/Klipper-CAN-Toolboards#3]
Hello

Connecting new sht36 and utoc1 boards to printer

A printer that used to work fine before

MCU 'sht36' shutdown: Timer too close

Problem occurs repeatedly at the same location in a specific g code

Did you have solution?

[klippy (1).zip](https://github.com/Mellow-3D/Klipper-CAN-Toolboards/files/8644865/klippy.1.zip)

**Comment by Solders2004** [comment]
I have the same problem with the same config(((
MCU 'sht36' shutdown: Timer too close
[klippy (15).log](https://github.com/Mellow-3D/Klipper-CAN-Toolboards/files/8682888/klippy.15.log)

**Comment by kluoyun** [comment]
> I have the same problem with the same config((( MCU 'sht36' shutdown: Timer too close [klippy (15).log](https://github.com/Mellow-3D/Klipper-CAN-Toolboards/files/8682888/klippy.15.log)

![image](https://user-images.githubusercontent.com/31061246/168193623-52207d63-4f23-4cd4-8a74-5b52b549ccca.png)
Found in your log, can buffer is too small. You need to set bigger data buffer
https://mellow.klipper.cn/?lang=en#/advanced/can_rpi

**Comment by Solders2004** [comment]
thank you! it helped!
<img width="493" alt="image" src="https://user-images.githubusercontent.com/83134078/168342197-7b39fb00-048c-450a-af12-e1817d0fbf11.png">
