### ISSUE TITLE
FLY UTOC

### ISSUE THREAD

**Issue by Sineos** [Mellow-3D/Klipper-CAN-Toolboards#4]
Silkscreen with respect to the JTAG header on my UTOC-1 is wrong. DIO and CLK are switched.

Please be so kind to release a schematic as well

**Comment by Rexsell** [comment]
I know, not an issue, but can you copy please share the copyed firmware of utoc board? Mine seems to be wrong firmware

**Comment by Sineos** [comment]
I made a backup of my UTOC but no warranty whatsoever

[Mellow_FLY_UTOC-1_STLink.zip](https://github.com/Mellow-3D/Klipper-CAN-Toolboards/files/9566759/Mellow_FLY_UTOC-1_STLink.zip)

**Comment by Seriyv0lk** [comment]
Yes! Please be so kind to release a schematic as well!!!
