### ISSUE TITLE
FLY SHT36 V2.0 missing

### ISSUE THREAD

**Issue by Mynasru** [Mellow-3D/Klipper-CAN-Toolboards#5]
The info of version 2.0 of this board is missing.

**Comment by jaysuk** [comment]
I'll hopefully have it up in the morning.

**Comment by Mynasru** [comment]
Thank you!
Fixed in https://github.com/Mellow-3D/Klipper-CAN-Toolboards/commit/6354d50348ab6001f940dfbde1e17d46d073f879
