### ISSUE TITLE
UTOC issue

### ISSUE THREAD

**Issue by Rexsell** [Mellow-3D/Klipper-CAN-Toolboards#6]
Can you please share the UTOC board .bin .hex firmware? I have issues with it's work, it not blinks while im connecting it to the raspberry. Also, no CAN uuids cant be displayed, and command sudo can-enable -d can0 -b 500000 -t 1024 says that no can0 devices found

**Comment by MarvinBeym** [comment]
You can flash the candlelight firmware onto the UTOC if you want.
=> https://maz0r.github.io/klipper_canbus/controller/candlelight_fw.html

Generally you should not have to flash any firmware onto the UTOC boards. They come with firmware pre-flashed (some early early sold units had a wrong/not working firmware on them, unlikely you have one of them!)


This page may also be worth to read for you:
https://maz0r.github.io/klipper_canbus/controller/utoc1-3.html

it also has a link to the firmware that is on the utoc's (it's likely candlelight as well)


Did you create the ``can0`` interface on your RPI?
